name: Ubuntu (2.x taosdump Release)

on:
  schedule:
    - cron: "10 16 * * *"
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

env:
  TOOLS_BUILD_TYPE: Release
  PR_NUMBER: ${{ github.event.number }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Step that prints name of pull request's base branch
        run: |
          echo "Pull request's base branch is: ${BASE_BRANCH}"
          echo "Pull request's branch is: ${GITHUB_REF##*/}"
          echo "Pull request's head ref is: ${GITHUB_HEAD_REF}"
        env:
          BASE_BRANCH: ${{ github.base_ref }}
        if: github.event_name == 'pull_request'

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # OR "2" -> To retrieve the preceding commit.

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v23.2

      - name: List all changed files
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "$file was changed"
          done

      - name: Get specific changed files
        id: changed-files-specific
        uses: tj-actions/changed-files@v23.2
        with:
          files: |
            src/CMakeLists.txt
            src/taosdump*
            tests/taosdump/native/*
            inc/*
            deps/CMakeLists.txt
            packaging/tools/*
            .github/workflows/*taosdump*

      - name: Run step if any of the listed files above change
        if: steps.changed-files-specific.outputs.any_changed == 'true'
        run: |
          echo "One or more files listed above has changed."

      - name: Checkout TDengine 2.6
        if: steps.changed-files-specific.outputs.any_changed == 'true'
        uses: actions/checkout@v2
        with:
          submodules: recursive
          repository: 'taosdata/TDengine'
          path: 'TDengine'
          ref: '2.6'

      - name: Change time zone
        if: steps.changed-files-specific.outputs.any_changed == 'true'
        run: |
          sudo timedatectl set-timezone Asia/Shanghai
          sudo date

          #- name: Checkout TDengine with same branch of taos-tools
          #run: |
          #cd TDengine
          #git pull
          #git branch -a | grep -w ${{ github.head_ref }} && git checkout ${{ github.head_ref }} || echo "${{ github.head_ref }} not found in TDengine"
          #git submodule update --init --recursive
          #if: github.event_name == 'pull_request'

      - name: Checkout TDengine's taos-tools to PR number
        if: |
          steps.changed-files-specific.outputs.any_changed == 'true' &&
          github.event_name == 'pull_request'
        run: |
          cd TDengine/src/kit/taos-tools
          git fetch origin +refs/pull/${{env.PR_NUMBER}}/merge
          git checkout -qf FETCH_HEAD

      - name: Set up Go
        if: steps.changed-files-specific.outputs.any_changed == 'true'
        uses: actions/setup-go@v3
        with:
          go-version: 1.17

      - name: Build & Install TDengine
        if: steps.changed-files-specific.outputs.any_changed == 'true'
        run: |
          sudo apt install libjansson-dev libsnappy-dev liblzma-dev libz-dev zlib1g pkg-config -y
          cd TDengine && mkdir release && cd release && cmake .. -DBUILD_JDBC=false -DBUILD_TOOLS=true -DTOOLS_BUILD_TYPE=${{env.TOOLS_BUILD_TYPE}} -DBUILD_HTTP=false && make -j8 && sudo make install
          if [[ ! -f /usr/local/bin/taosdump ]] && [[ ! -f /usr/local/bin/taosBenchmark ]]
          then
            echo "taos-tools build failure"
            exit 1
          fi
          pip3 install decorator numpy fabric2 psutil pandas faker toml taospy > /dev/null

      - name: taosdump Func Test
        if: steps.changed-files-specific.outputs.any_changed == 'true'
        run: |
          cd TDengine/tests/pytest
          sudo pkill -9 taosadapter || :
          sudo pkill -9 taosd || :

          if find tools -name "taosdump*.py"|grep -q .;
          then
            for i in `find tools -name "taosdump*.py"`;       \
              do python3 ./test.py -f $i > /dev/null          \
                && echo -e "\033[32m $i success! \033[0m"     \
                            | tee -a ~/taosdump-success.txt   \
                || echo -e "\033[31m $i failed! \033[0m"      \
                            | tee -a ~/taosdump-failed.txt;   \
                            done
          fi

      - name: taosdump System Test
        if: steps.changed-files-specific.outputs.any_changed == 'true'
        run: |
          cd TDengine/tests/system-test
          sudo pkill -9 taosadapter || :
          sudo pkill -9 taosd || :
          if find 5-taos-tools/taosdump -name "*.py"|grep -q .;
          then
            for i in `find 5-taos-tools/taosdump -name "*.py"`;       \
              do python3 ./test.py -f $i > /dev/null                  \
                && echo -e "\033[32m system-test/$i success! \033[0m" \
                            | tee -a ~/taosdump-success.txt           \
                || echo -e "\033[31m system-test/$i failed! \033[0m"  \
                            | tee -a ~/taosdump-failed.txt;           \
                            done
          fi

      - name: taosdump Old Test
        if: steps.changed-files-specific.outputs.any_changed == 'true'
        run: |
          cd TDengine/tests/system-test
          sudo pkill -9 taosadapter || :
          sudo pkill -9 taosd || :
          python3 test.py -f 5-taos-tools/TD-12478.py > /dev/null \
            && echo -e "\033[32m  system-test/5-taos-tools/TD-12478.py success! \033[0m"  \
                            | tee -a ~/taosdump-success.txt                               \
            || echo -e "\033[31m system-test/5-taos-tools/TD-12478.py failed! \033[0m"    \
                            | tee -a ~/taosdump-failed.txt

      - name: taosdump Develop Test
        if: steps.changed-files-specific.outputs.any_changed == 'true'
        run: |
          cd TDengine/src/kit/taos-tools/tests
          sudo pkill -9 taosadapter || :
          sudo pkill -9 taosd || :

          if find taosdump/native -name "*.py"|grep -q .;
          then
            for i in `find taosdump/native -name "*.py"`; \
              do python3 ./test.py -f $i > /dev/null                    \
                && echo -e "\033[32m develop-test/$i success! \033[0m"  \
                            | tee -a ~/taosdump-success.txt             \
                || echo -e "\033[31m develop-test/$i failed! \033[0m"   \
                            | tee -a ~/taosdump-failed.txt ;            \
                            done
          fi

      - name: taosdump special Develop Test
        if: steps.changed-files-specific.outputs.any_changed == 'true'
        run: |
          cd TDengine/src/kit/taos-tools/tests
          sudo pkill -9 taosadapter || :
          sudo pkill -9 taosd || :

          if find taosdump/native2 -name "*.py"|grep -q .;
          then
            for i in `find taosdump/native2 -name "*.py"`;    \
              do python3 ./test.py -f $i > /dev/null          \
                && echo -e "\033[32m $i success! \033[0m"     \
                            | tee -a ~/taosdump-success.txt   \
                || echo -e "\033[31m $i failed! \033[0m"      \
                            | tee -a ~/taosdump-failed.txt;   \
                            done
          fi

      - name: Check Test Result
        if: steps.changed-files-specific.outputs.any_changed == 'true'
        run: |
          if [ -f ~/taosdump-failed.txt ]; then
            cat ~/taosdump-failed.txt
            exit 1
          elif [ -f ~/taosdump-success.txt ]; then
            cat ~/taosdump-success.txt
          fi
